#!/bin/bash

# A simple guessing game
# Author: Tega

# This is similar to the guesser script but here we initialize our variables as integers
# This allows us to use arithmetic operations directly in our code

# Get a random number < 100
# The -i declares the "target variable as an integer"
# The -r declares it as a readonly value
declare -ir target=$((( $RANDOM % 100 ) + 1))

# Initialize the user's guess as an integer
declare -i guess=0

until (( $guess == $target )); do
  read -p "Take a guess: " guess

  # if guess is 0, then it was not a number
  (( guess )) || continue

  if (( $guess < $target )); then
    echo "Higher!"
  elif (( $guess > $target )); then
    echo "Lower!"
  else
    echo "Eureka, you found it!!!"
  fi
done

exit 0