#!/bin/bash -x

# N.B the "-x" option aboves causes the commands and their arguments to be printed during script execution.
# Check man /bin/bash for more info

# Simple note-taking script
# Author: Tega

# Get the date
date=$(date)

# Get the topic
topic="$1"

# Filename to write to
filename="${HOME}/Desktop/${topic}notes.txt"

# Ask user for input
read -p "Your note: " note

if [[ $note ]]; then
  echo "$date: $note" >> "$filename"
  echo "Note '$note' saved to $filename"
else
  # 0 --> stdin, 1 --> stdout, 2 --> stderr
  # /dev/stderr is the special output file for standard errors
  echo "No input; note was not saved"  1>&2
fi